# Generated by Django 5.2.3 on 2025-06-23 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shorturls', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shorturls',
            name='user',
        ),
    ]
